---
title: Trabalho de Estatística Computacional sobre erros Tipo I e Tipo II    
author:    
   - Rafael Alisson Schipiura    
   - Matheus Born Cabús 
date: 9 de Abril de 2024    
fontsize: 8pt    
output:    
   beamer_presentation:    
      slide_level: 2    
      latex_engine: xelatex
---

```{r echo=FALSE}
options(digits=3)
RNGkind("Mersenne-Twister")
RNGversion("4.1.2")
set.seed(1752031105)
library(formatR)
knitr::opts_chunk$set(tidy.opts = list(width.cutoff = 50), tidy = TRUE)
```

## Parâmetros 

```{r}
main <- function(){
   tamanhos <- 3 * 10 ^ c(0:3)
   significancias <- c(0.1, 0.05, 0.01)
   distribuicoes <- c('Normal', 'Poisson')#, 'Gamma', 'Exponencial')
   for (d in distribuicoes){
   trabalho(tamanhos, significancias, d)
   }
}
```

## Para cada distribuição:

```{r}
trabalho <- function(tamanhos_m, significancias_m, distro_m){
   simulacoes <- 300
   pontos <- 10
   resul_amostras <- vector("list",length(tamanhos_m))
   for(n in 1:length(tamanhos_m)){
      resul_amostras[[n]] <- simula_s(tamanhos_m[n], significancias_m, distro=distro_m, pontos_s=pontos, sim_amos=simulacoes)
   }
   names(resul_amostras) <- tamanhos_m
   slides(resul_amostras, paste0("Distribuição ", distro_m, ", n ="))
   
   resul_signif <- vector("list",length(significancias_m))
   for(s in 1:length(significancias_m)){
      resul_signif[[s]] <- simula_n(tamanhos_m, significancias_m[s], distro=distro_m, pontos_n=pontos, sim_amos=simulacoes)
   }
   names(resul_signif) <- significancias_m
   slides(resul_signif, paste0("Distribuição ", distro_m, ", $\\alpha$ ="))

}

```

## Teste 

```{r}
teste <- function(amostra_i, amostra_j, sig_i = 0.05){
   return((t.test(amostra_i, amostra_j))$p.value < sig_i)
}

```

## Sorteio da amostra 

```{r}

amostra <- function(n_a, distro, param1, param2){
   
   if       (distro == 'Normal'){
      return(rnorm(n_a, mean=param1, sd=param2))
   } else if(distro == 'Poisson'){
      return(rpois(n_a, lambda=param1))
   } else if(distro == 'Gamma'){
      return(rgamma(n_a, shape=param1/param2, scale=param2))
   } else if(distro == 'Exponencial'){
      return(rexp(n_a, rate=1/param1))
   }
}

```

## Sorteamos uma amostra e executamos os testes pra cada significância 

```{r echo=FALSE}

varia_n <- function(n_n, sig_n, tipoII=FALSE, distro_n, param_n = 20, pontos){
   
   amostra_n <- amostra(max(n_n), distro=distro_n, param1=param_n, param2=2)
   amostra_m <- amostra(max(n_n), distro=distro_n, param1=param_n + 0.5 * tipoII, param2=3)

   n10 <- floor(seq(from=min(n_n), to=max(n_n), length.out=pontos))
   resultado <- logical(length=pontos) 
   for(n_j in 1:pontos){
      resultado[n_j] <- teste( sample(amostra_n, n10[n_j]), sample(amostra_m, n10[n_j]), sig_n)

   }
   return(resultado)
}

```

```{r}

varia_s <- function(n_s, sig_s, tipoII=FALSE, distro_s, param_s = 20, pontos){
   amostra_s <- amostra(n_s, distro=distro_s, param1=param_s, param2=2)
   amostra_r <- amostra(n_s, distro=distro_s, param1=param_s + 0.5 * tipoII, param2=3)

   s10 <- seq(from=min(sig_s), to=max(sig_s), length.out=pontos)
   resultado <- logical(length=pontos) 
   for(s_j in 1:pontos){
      resultado[s_j] <- teste(amostra_s, amostra_r, s10[s_j])
   }
   return(resultado)
}

```

## Simulação amostral

```{r echo=FALSE}
simula_n <- function(n_n, sig_n, distro, pontos_n, sim_amos){
   D3 <- array(dim=c(pontos_n, 2, sim_amos))
   for(i in 1:sim_amos){
	   D3[,1,i] <- varia_n(n_n, sig_n, tipoII=FALSE, distro_n=distro, pontos=pontos_n)
	   D3[,2,i] <- !(varia_n(n_n, sig_n, tipoII=TRUE, distro_n=distro, pontos=pontos_n))
   }
   result <- apply(D3, MARGIN=c(1,2), FUN=mean)
   colnames(result) <- c("Tipo I", "Tipo II")
   return(result)
}
```

```{r}

simula_s <- function(n_s, sig_s, distro, pontos_s, sim_amos){
   D3 <- array(dim=c(pontos_s, 2, sim_amos))
   for(i in 1:sim_amos){
	   D3[,1,i] <- varia_s(n_s, sig_s, tipoII=FALSE, distro_s=distro, pontos=pontos_s)
	   D3[,2,i] <- !(varia_s(n_s, sig_s, tipoII=TRUE, distro_s=distro, pontos=pontos_s))
   }
   result <- apply(D3, MARGIN=c(1,2), FUN=mean)
   colnames(result) <- c("Tipo I", "Tipo II")
   return(result)
}
```

## Resultado 

```{r, results='asis'}
slides <- function(lista, titulo){
   for(l in names(lista)){
      cat("\n## ", titulo, " ", l, "\n\n")
      #cat(knitr::kable(lista[[l]], "latex"), "\n\n")
      plot(lista[[l]], type='l', xlim=c(0.001,0.122), ylim=c(0, 1))
      abline(v=c(0.1, 0.05, 0.01))
      cat("\n\n")
   }
}

main()
```
