---
title: |
   | Estatística Computacional
   | Erros Tipo I e Tipo II    
author:    
   - Rafael Alisson Schipiura
   - Matheus Born Cabús 
date: 9 de Abril de 2024    
output:    
   beamer_presentation:    
      theme: "Antibes"
      colortheme: "beaver"
      fonttheme: "structurebold"
      slide_level: 3 
      latex_engine: xelatex
---

```{r, echo=FALSE}
options(digits=3)
RNGkind("Mersenne-Twister")
RNGversion("4.1.2")
set.seed(1752031105)
library(formatR)
library(ggplot2)
library(reshape2)
library(RColorBrewer)
knitr::opts_chunk$set(tidy.opts = list(width.cutoff = 50), tidy = TRUE)
knitr::opts_chunk$set(dev = 'pdf', fig.width=4.5, fig.height=2.5, fig.align='center')
teste <- function(amostra1, amostra2, qual, sig){
	if(qual == 'Teste t de Student'){
		teste <- t.test
	} else {
		teste <- wilcox.test
	}
	return(teste(amostra1, amostra2)$p.value < sig)
}
amostra <- function(n, distro, delta){

   if(distro == 'Poisson'){
      return(rpois(n, lambda=20+delta))
   } else if(distro == 'Gamma'){
      return(rgamma(n, shape=(20+delta)/2, scale=2))
   } else if(distro == 'Exponencial'){
      return(rexp(n, rate=1/(20+delta)))
   } else {
      return(rnorm(n, mean=20+delta, sd=2))
   }
}
f1 <- function(x){round(1 + 10.8073*x^3 - 0.778646*x^4 - 1.27604*x^5 + 0.247396*x^6, digits=0)}
f2 <- function(x){4 * 2^x}
```
```{r, echo=FALSE, results='asis'}
main <- function(){
   simulacoes <- c('Curva do Poder do Teste','Trade-Off Beta')
   distros <- c('Normal', 'Exponencial', 'Gamma')
   testes <- c('Teste t de Student', 'Teste de Wilcoxon')
   ndeltas <- 29 
   deltas <- seq(from=-3, to=3, length.out=ndeltas)
   delta_fixo <- 0.1
   h1 <- 1
   numalphas <- f2(h1)
   seql <- (4 * 0:numalphas)/numalphas
   alphas <- f1(seql)/1000
   alpha_fixo <- 0.05
   num_enes <- 4
   enes <- 3 * 10^(0:(num_enes-1))
   size <- 3000 

   resultado <- vector('list', length(simulacoes))
   names(resultado) <- simulacoes
   for(i in names(resultado)){
      cat("# ", i, "\n\n")
      resultado[[i]] <- vector('list', length(distros))
      names(resultado[[i]]) <- distros
      for(j in names(resultado[[i]])){
         cat("## Distribuição", j, "\n\n")
         resultado[[i]][[j]] <- vector('list', length(testes))
         names(resultado[[i]][[j]]) <- testes
	 for(k in names(resultado[[i]][[j]])){
	    cat("### ", k, "\n\n")
            if (i == 'Trade-Off Beta'){
	       primeira <- length(alphas)
	       nomes <- paste0(round(alphas * 100, digits=2), "%")
	       alpha <- alphas 
	       delta <- rep(delta_fixo, primeira)
            } else {
               primeira <- ndeltas
	       nomes <- deltas
	       alpha <- rep(alpha_fixo, primeira)
	       delta <- deltas
	    }
            d3 <- array(dim=c(num_enes, primeira, size), dimnames=list(n=enes, d=nomes))
   for(p in 1:primeira){
	    for(n in 1:num_enes){
		    d3[n, p,] <- replicate(size, teste(amostra(enes[n], j, 0), amostra(enes[n], j, delta[p] ), k , alpha[p]))
	       }
	    }
	    matriz <- apply(d3, MARGIN=c(1,2), FUN=mean)
            if (i == 'Trade-Off Beta'){
	       matriz_longa <- melt(matriz)
	       matriz_longa$n <- sprintf("%04d",matriz_longa$n)
               print(ggplot(data=matriz_longa, aes(x=n, y=d)) +
		     geom_tile(aes(fill = value), color = "white", lwd = 0.1, linetype = 1) + 
		     theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) + 
		     guides(fill = guide_colourbar(barwidth = 0.5, barheight = 8, title = "Poder")) + xlab("Tamanho da Amostra") + ylab("Significância") +
		     geom_text(aes(label = sprintf('%.02f%%', 100*value)), color = "white", size = 3))
	    } else {
	       matriz_longa <- melt(matriz)
	       plot <- ggplot(data= matriz_longa, aes(x=d))
	       nomes_legenda <- sprintf("%04d", enes)
	       legenda <- brewer.pal(num_enes, "Set3")
	       for(l in 1:num_enes){
	          #cat(knitr::kable(matriz_longa[matriz_longa$n==l,], 'latex'))
	          select <- matriz_longa[matriz_longa$n==enes[l],]
	          select$cor <- rep(nomes_legenda[l], nrow(select))
	          plot <- plot + geom_line(data=select, aes(y=value, color=cor))
	       }
	       plot <- plot + scale_color_manual(name='n', breaks=nomes_legenda, values=legenda) + xlab("Delta") + ylab("Poder")# + geom_vline(xintercept=c(c(-1,1)%*%t(c(0.5, 1.5))))
	       print(plot)
	    }
	    cat("\n\n")
         }
      }
   }
}
main()
```
